name: superai-ta
services:
  - name: api
    source_dir: /
    github:
      repo: rurumeister/superai-ta
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    dockerfile_path: Dockerfile
    envs:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ${postgres.HOSTNAME}
      - key: DB_PORT
        value: ${postgres.PORT}
      - key: DB_NAME
        value: ${postgres.DATABASE}
      - key: DB_USER
        value: ${postgres.USERNAME}
      - key: DB_PASSWORD
        value: ${postgres.PASSWORD}
      - key: BASE_URL
        value: ${APP_URL}
      - key: DEBUG
        value: "true"
    http_port: 3000
    health_check:
      http_path: /api/health

  - name: migration-worker
    source_dir: /
    github:
      repo: rurumeister/superai-ta
      branch: main
    run_command: npm run db:migrate
    environment_slug: node-js
    instance_count: 0
    instance_size_slug: basic-xxs
    dockerfile_path: Dockerfile
    envs:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ${postgres.HOSTNAME}
      - key: DB_PORT
        value: ${postgres.PORT}
      - key: DB_NAME
        value: ${postgres.DATABASE}
      - key: DB_USER
        value: ${postgres.USERNAME}
      - key: DB_PASSWORD
        value: ${postgres.PASSWORD}

databases:
  - name: postgres
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
    db_name: db
    id: e832ce2d-d8e5-4aad-b8ab-f08c8fea1a17
